- name: High School Teacher Maintenance Configuration
  hosts: localhost
  become: yes

  tasks:
    - include: tasks/removePackages.yml
    - include: tasks/addPackages.yml
    - include: tasks/cronJobs.yml