- name: install cron job (ansible-pull)
  cron: 
    user: user
    name: "ansible update" 
    minute: "*/10" 
    job: "/usr/bin/ansible-pull -o -U https://github.com/West-Fork-Tech-Department/hs-teacher-ansible-pulls.git > /dev/null"